port: 8080
name: Penguin Server
logging:
  level: info
  # loggingTransports:
  #  - transport: console
  #    options:
  #      stringify: true
  #      json: true
# swagger:
#   enableValidation: true
#   enableRedirectRoot: true
# cors:
#   origin: "*"
data:
  source: memory
preferences:
  source: memory
gitlabUrl: "https://gitlab.com"